name: habit_habibi
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1

  # Utility
  flutter_local_notifications: ^17.0.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.8

  # UI & Animation
  flutter_animate: ^4.5.0 # A powerful and easy-to-use animation library
  google_fonts: ^6.2.1 # For modern, clean fonts (latest version kept)
  lottie: ^3.0.0 # Excellent for complex, pre-made animations (e.g., loading screens)
  shimmer: ^3.0.0 # Great for creating loading skeletons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # Corrected to a stable, recommended version

flutter:
  uses-material-design: true
